app:
  name: "hono-skeleton"
  env: "development"
  port:
    http: 8080
    https: 8443
  path:
    cert: "./internal/assets/dev/tls/zercle-dev.crt"
    priv: "./internal/assets/dev/tls/zercle-dev.key"
    ca: "./internal/assets/dev/tls/rootCA.crt"
    log: "./log"
db:
  postgres:
    sock: "/var/run/postgresql"
    host: "localhost"
    port: 15432
    username: "postgres"
    password: "SkillSyncPassword"
    db_name: "postgres"
    conn:
      min: 1
      max: 2
  redis:
    host: "localhost"
    port: 16379
    username: ""
    password: ""
    db_name: 0

jwt:
  private: "./internal/assets/dev/jwt/privkey.pem"
  public: "./internal/assets/dev/jwt/pubkey.pem"
